#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# shellcheck disable=SC1091
source "$SCRIPT_DIR/common"

if test "$#" -ne 3; then
    fail "Usage: $0 IMAGE QUERY DISK_SIZE"
fi

IMAGE="$1"
shift

QUERY="$1"
shift

DISK_SIZE="$1"
shift

JSON=$(vastai search offers "$QUERY disk_space >= $DISK_SIZE" -o dph --raw)

if test "$JSON" == ""; then
    fail "No response"
fi

if ! echo "$JSON" | jq > /dev/null; then
    fail "Invalid JSON: $JSON"
fi

ACCEPT=0
INDEX=0
while test "$ACCEPT" -eq 0; do
  COST=$(echo "$JSON" | jq '.['"$INDEX"']["dph_total"] *100|round/100' -r)
  MONTHLY_COST=$(echo "$JSON" | jq '.['"$INDEX"']["dph_total"] * (30 * 8)|round' -r)
  OFFER_ID=$(echo "$JSON" | jq '.['"$INDEX"']["id"]' -r)
  CUDA_MAX_GOOD=$(echo "$JSON" | jq '.['"$INDEX"']["cuda_max_good"]' -r)
  CPU_NAME=$(echo "$JSON" | jq '.['"$INDEX"']["cpu_name"] | trim | gsub("[®™©]"; "")' -r)
  CPU_RAM=$(echo "$JSON" | jq '.['"$INDEX"']["cpu_ram"]' -r)
  GPU_COUNT=$(echo "$JSON" | jq '.['"$INDEX"']["num_gpus"]' -r)
  GPU_NAME=$(echo "$JSON" | jq '.['"$INDEX"']["gpu_name"] | trim' -r)
  GPU_RAM=$(echo "$JSON" | jq '.['"$INDEX"']["gpu_ram"]' -r)
  GPU_TOTAL_RAM=$(echo "$JSON" | jq '.['"$INDEX"']["gpu_total_ram"]' -r)
  # shellcheck disable=SC2034
  HOST_ID=$(echo "$JSON" | jq '.['"$INDEX"']["host_id"]' -r)
  # shellcheck disable=SC2034
  MACHINE_ID=$(echo "$JSON" | jq '.['"$INDEX"']["machine_id"]' -r)
  GEOLOCATION=$(echo "$JSON" | jq '.['"$INDEX"']["geolocation"] | gsub("^[, ]+|[, ]+$"; "")' -r)

  COMPUTE_CAP=$(echo "$JSON" | jq '.['"$INDEX"']["compute_cap"] | . / 100 | tostring | if test("\\.") then . else . + ".0" end' -r)

  DOWNLOAD_SPEED=$(echo "$JSON" | jq '.['"$INDEX"']["inet_down"]' -r)
  DOWNLOAD_COST=$(echo "$JSON" | jq '.['"$INDEX"']["inet_down_cost"] * 10000 | round / 10000' -r)
  UPLOAD_COST=$(echo "$JSON" | jq '.['"$INDEX"']["inet_up_cost"] * 10000 | round / 10000' -r)
  FULL_SIZE_DOWNLOAD_SECONDS=$(python -c "print(int($DISK_SIZE * 8 * 1024 / $DOWNLOAD_SPEED))")
  FULL_SIZE_DOWNLOAD_TRAFFIC_COST=$(python -c "print(0.018 * $UPLOAD_COST * $DISK_SIZE + $DOWNLOAD_COST * $DISK_SIZE)")
  FULL_SIZE_DOWNLOAD_RENTAL_COST=$(python -c "print($COST * ($FULL_SIZE_DOWNLOAD_SECONDS / (60 * 60)))")
  FULL_SIZE_DOWNLOAD_COST=$(python -c "print($FULL_SIZE_DOWNLOAD_TRAFFIC_COST + $FULL_SIZE_DOWNLOAD_RENTAL_COST)")

  WORKING_MONTH_COST=$(python -c "print(21 * ($COST * 8 + $FULL_SIZE_DOWNLOAD_COST))")

  log "Offer $OFFER_ID:
    GPU: ${GPU_COUNT}x $GPU_NAME (${GPU_COUNT}x $((GPU_RAM / 1024)) GB = $((GPU_TOTAL_RAM / 1024)) GB)
    CPU: $CPU_NAME ($((CPU_RAM / 1024)) GB)
    Location: $GEOLOCATION
    Cost: $COST USD/h ($MONTHLY_COST USD/month)
    Maximum CUDA: $CUDA_MAX_GOOD
    Compute capability: $COMPUTE_CAP
    Download speed: $DOWNLOAD_SPEED Mb/s
    Download cost: $DOWNLOAD_COST USD/GB
    Time for downloading $DISK_SIZE GB: $(python -c "print(f'{$FULL_SIZE_DOWNLOAD_SECONDS // 3600}h {$FULL_SIZE_DOWNLOAD_SECONDS % 3600 // 60}m')")
    Cost of $DISK_SIZE GB in traffic: $(python -c "print(f"'"'"{$FULL_SIZE_DOWNLOAD_TRAFFIC_COST:.2f}"'"'")") USD
    Total cost of downloading $DISK_SIZE GB: $(python -c "print(f"'"'"{$FULL_SIZE_DOWNLOAD_COST:.2f}"'"'")") USD
    Working month cost: $(python -c "print(f"'"'"{$WORKING_MONTH_COST:.0f}"'"'")") USD/month"
  if ask "Launch? [yn]"; then
    ACCEPT=1
  fi
  log ""
  INDEX=$((INDEX+1))
done

IMAGE=$(echo "$IMAGE" | sed 's/%COMPUTE_CAP%/'"$COMPUTE_CAP"'/')
INSTANCE_OUTPUT=$(
    vastai create instance \
           "$OFFER_ID" \
           --image "$IMAGE" \
           --disk "$DISK_SIZE" \
           --raw \
           --env '-e SSH_PUBLIC_KEY="'"$(cat ~/.ssh/id_ed25519_datacrunch.pub)"'"' \
           --direct \
           --args
)

RESULT=$(echo "$INSTANCE_OUTPUT" | jq '.["success"]')
if test "$RESULT" != "true"; then
    fail "Instance creation failed: $(echo "$INSTANCE_OUTPUT" | jq)"
fi

CONTRACT_ID=$(echo "$INSTANCE_OUTPUT" | jq '.["new_contract"]')

log "Successfully created contract $CONTRACT_ID"

log "Waiting for the instance to become available"
while test "$(vastai show instance "$CONTRACT_ID" --raw | jq '.["actual_status"]' -r)" != "running"; do
    sleep 1
done

SSH_URL=$(vastai ssh-url "$CONTRACT_ID")
log "The machine is up at $SSH_URL, waiting for SSH to be available"

SSH=("${SSH_PREFIX[@]}")
SSH+=("$SSH_URL")

while test "$("${SSH[@]}" 'echo ready' 2> /dev/null)" != "ready"; do
    sleep 1
done

log "GPU info"
stderr "${SSH[@]}" /nix/store/*-glibc-*/lib/ld-linux-x86-64.so.2 /usr/bin/nvidia-smi

log "SSH available: ${SSH[*]}"
echo "$SSH_URL"
