#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPT_DIR/common"

SSH_URL=$(
    "$SCRIPT_DIR/create-instance" \
        'ghcr.io/aleclearmind/vast-ai-nix-container-base' \
        'gpu_ram > 4 compute_cap >= 750 cuda_max_good >= 12.9 inet_down >= 300' \
        128
)

SSH=("${SSH_PREFIX[@]}")
SSH+=("$SSH_URL")

log "Preparing whisper"
# shellcheck disable=SC2016
"${SSH[@]}" '
set -euo pipefail
cd /root
# TODO: not necessary
export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
source /etc/profile.d/nix.sh
CAPABILITIES=$(/nix/store/*-glibc-*/lib/ld-linux-x86-64.so.2 --library-path /usr/lib/x86_64-linux-gnu/ /usr/bin/nvidia-smi --query-gpu=compute_cap --format=csv,noheader)
nix profile add self-ai#"\"whisper\""
whisper-cpp-download-ggml-model large-v3
wget "https://huggingface.co/ggml-org/whisper-vad/resolve/main/ggml-silero-v5.1.2.bin"
'


PORT=39823
log "Launching whisper on $PORT"
# shellcheck disable=SC2016
"${SSH[@]}" \
    -L "$PORT":localhost:"$PORT" \
    '
cd /root
# TODO: not necessary
export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu"
source /etc/profile.d/nix.sh
whisper-server \
  -m ggml-large-v3.bin \
  --convert \
  --print-colors \
  --print-realtime \
  --print-progress \
  --vad-model ggml-silero-v5.1.2.bin \
  --vad \
  --max-context 64 \
  --language auto \
  --port '"$PORT"'
'
