#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPT_DIR/common"

MODELS_YAML="$SCRIPT_DIR/llm-models.yml"

if test "$#" -ne 1; then
    log "Usage: $0 MODEL_NAME"
    log ""
    log "Available models:"
    yq -r 'keys() | .[]' < "$MODELS_YAML" | sed 's|^|    |' >& /dev/stderr
    exit 1
fi

MODEL_NAME="$1"
shift

yaml_export "$MODELS_YAML" "$MODEL_NAME"

SSH_URL=$("$SCRIPT_DIR/create-instance" 'gpu_ram >= '"$MINIMUM_GPU_RAM"' cuda_max_good = "12.8" geolocation != "US"' "$MODEL_SIZE")

SSH=("${SSH_PREFIX[@]}")
SSH+=("$SSH_URL")

log "Installing nix"
"${SSH[@]}" '
set -euo pipefail

apt-get install -y xz-utils

sh <(curl --proto "=https" --tlsv1.2 -L https://nixos.org/nix/install) --daemon --yes

cat > /etc/nix/nix.conf <<EOF
extra-substituters = https://cache.flox.dev https://nix-community.cachix.org https://cache.nixos-cuda.org
extra-trusted-substituters = https://cache.flox.dev https://nix-community.cachix.org https://cache.nixos-cuda.org
extra-trusted-public-keys = flox-cache-public-1:7F4OyH7ZCnFhcze3fJdfyXYLQw/aV7GEed86nQ7IsOs= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M=
extra-experimental-features = flakes nix-command
EOF
'

OLLAMA="nix run --override-input nixpkgs nixpkgs/nixos-25.11 github:aleclearmind/self-ai#ollama --"
log "Installing ollama"
"${SSH[@]}" "$OLLAMA --help"

log "Fetching model"
"${SSH[@]}" "
$OLLAMA serve &
sleep 3
$OLLAMA pull $OLLAMA_MODEL_NAME
pkill ollama
"

log "Launching ollama"
PORT=20512
"${SSH[@]}" \
    -L "$PORT":localhost:"$PORT" \
    "OLLAMA_HOST=127.0.0.1:$PORT $OLLAMA serve"
