#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPT_DIR/common"

MODELS_YAML="$SCRIPT_DIR/llm-models.yml"

if test "$#" -ne 1; then
    log "Usage: $0 MODEL_NAME"
    log ""
    log "Available models:"
    yq -r 'keys() | .[]' < "$MODELS_YAML" | sed 's|^|    |' >& /dev/stderr
    exit 1
fi

MODEL_NAME="$1"
shift

yaml_export "$MODELS_YAML" "$MODEL_NAME"

# 'ghcr.io/aleclearmind/vast-ai-nix-vllm-%COMPUTE_CAP%'
SSH_URL=$(
    "$SCRIPT_DIR/create-instance" \
        'ghcr.io/aleclearmind/vast-ai-nix-container-base' \
        'gpu_ram >= '"$MINIMUM_GPU_RAM"' compute_cap == 1200 inet_down >= 1000' \
        "$((MODEL_SIZE + 100))"
)

SSH=("${SSH_PREFIX[@]}")
SSH+=("$SSH_URL")

PORT=8000
log "Launching vllm on $PORT"
# shellcheck disable=SC2016
"${SSH[@]}" \
    -L "$PORT":localhost:"$PORT" \
    '
set -euo pipefail
cd /root
# TODO: not necessary
export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
source /etc/profile.d/nix.sh
CAPABILITIES=$(/nix/store/*-glibc-*/lib/ld-linux-x86-64.so.2 --library-path /usr/lib/x86_64-linux-gnu/ /usr/bin/nvidia-smi --query-gpu=compute_cap --format=noheader)
nix profile add self-ai#"\"vllm\""
'

PORT=8000
log "Launching vllm on $PORT"
# shellcheck disable=SC2016
"${SSH[@]}" \
    -L "$PORT":localhost:"$PORT" \
    '
export LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu"
source /etc/profile.d/nix.sh
vllm serve openai/gpt-oss-120b
'
