#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPT_DIR/common"

AUDIO_TMP="$(mktemp tmp.XXXXXXXXXX.opus)"
trap 'rm -f "$AUDIO_TMP"' exit

while test "$#" -gt 0; do
    INPUT_FILE="$1"
    shift
    OUTPUT_FILE="$INPUT_FILE.srt"

    AUDIO="$INPUT_FILE.opus"

    log "Processing $INPUT_FILE"

    if test -s "$OUTPUT_FILE"; then
        log "  Subtitles already available, skipping $INPUT_FILE"
        continue
    fi

    log "  Input file is $(prettysize "$INPUT_FILE")"

    if ! test -e "$AUDIO"; then
      log "  Extracting audio and normalizing"

      rm -f "$AUDIO_TMP"

      # -acodec copy
      # -ss $((60 * 0)) -to $((60 * 25))
      # -ss $((60 * 17)) -to $((60 * 25))
      # ffmpeg -i "$INPUT_FILE" -ar 16000 -ac 1 -c:a pcm_s16le "$AUDIO_TMP"
      # (sleep 1; pv -d $(pgrep ffmpeg):3 ) &
      if ! (
          set -m
          ffmpeg -v error -hide_banner -i "$INPUT_FILE" -vn -filter:a 'speechnorm=e=12.5:r=0.0001:l=1' "$AUDIO_TMP" &
          sleep 1
          pv -d "$(pgrep ffmpeg)":3
          fg
          set +m
      ); then
          log "  Couldn't extract audio!"
          continue
      fi

      mv "$AUDIO_TMP" "$AUDIO"
    fi

    log "  Extracted audio is $(prettysize "$AUDIO")"

    log "  Producing subtitles"
    PORT=39823
    curl http://127.0.0.1:"$PORT"/inference \
        -H "Content-Type: multipart/form-data" \
        -F file="@$AUDIO" \
        -F temperature="0.0" \
        -F entropy_thold="2.8" \
        -F temperature_inc="0.2" \
        -F response_format="srt" \
        > "$OUTPUT_FILE"

    rm "$AUDIO"
done
